Add OHBM Aperture citation
brainiak/brainiak.github.io pull request #75
Opened 2020-12-11 16:27 UTC by gdoubleyew

2020-12-11 16:43 UTC, manojneuro commented on _data/pubs.yml
> +  journal: OHBM Aperture
Please change "OHBM Aperture" to preprint.

2020-12-11 16:43 UTC, manojneuro commented on tutorials/index.md
> +
Please change "OHBM Aperture" to preprint.

2020-12-11 16:43 UTC, manojneuro commented on _data/pubs.yml
> +      - Peeta Y. Li
Please make this "Y. Peeta Li" (per author request). instead of Peeta Y. Li

2020-12-11 16:52 UTC, gdoubleyew commented
Here are the new screen shots
[cid:image001.png@01D6CFB4.12995570]
[cid:image002.png@01D6CFB4.12995570]



From: manojneuro <notifications@github.com>
Reply-To: "brainiak/brainiak.github.io" <reply@reply.github.com>
Date: Friday, December 11, 2020 at 11:43 AM
To: "brainiak/brainiak.github.io" <brainiak.github.io@noreply.github.com>
Cc: Grant Wallace <gwallace@princeton.edu>, Author <author@noreply.github.com>
Subject: Re: [brainiak/brainiak.github.io] Add OHBM Aperture citation (#75)


@manojneuro commented on this pull request.

________________________________

In _data/pubs.yml<https://github.com/brainiak/brainiak.github.io/pull/75#discussion_r541078374>:

> +      - Daniel Suo

+      - Javier S. Turek

+      - Vy A. Vo

+      - Grant Wallace

+      - Yida Wang

+      - Hejia Zhang

+      - Xia Zhu

+      - Mihai Capota

+      - Jonathan D. Cohen

+      - Uri Hasson

+      - Kai Li

+      - Peter J. Ramadge

+      - Nicholas B. Turk-Browne

+      - Theodore L. Willke

+      - Kenneth A. Norman

+  journal: OHBM Aperture

Please change "OHBM Aperture" to preprint.

________________________________

In tutorials/index.md<https://github.com/brainiak/brainiak.github.io/pull/75#discussion_r541078703>:

> @@ -420,6 +420,8 @@ We have compiled a list of useful resources that cover the basics of GitHUB, Pyt



 Like BrainIAK itself, these tutorials are open-sourced as a service to the field and can be freely used, modified, and shared. They are licensed under the Apache License, Version 2.0. If you find them helpful in your research or re-use code they contain, you might consider citing:



+Manoj Kumar, Michael J. Anderson, James W. Antony, Christopher Baldassano, Paula P. Brooks, Ming Bo Cai, Po-Hsuan Cameron Chen, Cameron T. Ellis, Gregory Henselman-Petrusek, David Huberdeau, J. Benjamin Hutchinson, Peeta Y. Li, Qihong Lu, Jeremy R. Manning, Anne C. Mennen, Samuel A. Nastase, Hugo Richard, Anna C. Schapiro, Nicolas W. Schuck, Michael Shvartsman, Narayanan Sundaram, Daniel Suo, Javier S. Turek, Vy A. Vo, Grant Wallace, Yida Wang, Hejia Zhang, Xia Zhu, Mihai Capota, Jonathan D. Cohen, Uri Hasson, Kai Li, Peter J. Ramadge, Nicholas B. Turk-Browne, Theodore L. Willke, Kenneth A. Norman, (2020, December 9). BrainIAK: The Brain Imaging Analysis Kit. OHBM Aperture, [https://doi.org/10.31219/osf.io/db2ev](https://doi.org/10.31219/osf.io/db2ev)

+

Please change "OHBM Aperture" to preprint.

________________________________

In _data/pubs.yml<https://github.com/brainiak/brainiak.github.io/pull/75#discussion_r541079554>:

> +- id: Kumar2020_12

+  title: "BrainIAK: The Brain Imaging Analysis Kit"

+  date: 2020-12-09

+  authors:

+      - Manoj Kumar

+      - Michael J. Anderson

+      - James W. Antony

+      - Christopher Baldassano

+      - Paula P. Brooks

+      - Ming Bo Cai

+      - Po-Hsuan Cameron Chen

+      - Cameron T. Ellis

+      - Gregory Henselman-Petrusek

+      - David Huberdeau

+      - J. Benjamin Hutchinson

+      - Peeta Y. Li

Please make this "Y. Peeta Li" (per author request). instead of Peeta Y. Li

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/brainiak/brainiak.github.io/pull/75#pullrequestreview-550260819>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AH7ZDPJATWY4A7NZJ5MNCBLSUJD27ANCNFSM4UW4AKZQ>.

2020-12-11 17:48 UTC, manojneuro commented on tutorials/index.md
> +
For consistency with the other citation, I have modified a few things (removed italics, and the month) below. Please use this:

Manoj Kumar, Michael J. Anderson, James W. Antony, Christopher Baldassano, Paula P. Brooks, Ming Bo Cai, Po-Hsuan Cameron Chen, Cameron T. Ellis, Gregory Henselman-Petrusek, David Huberdeau, J. Benjamin Hutchinson, Y. Peeta Li, Qihong Lu, Jeremy R. Manning, Anne C. Mennen, Samuel A. Nastase, Hugo Richard, Anna C. Schapiro, Nicolas W. Schuck, Michael Shvartsman, Narayanan Sundaram, Daniel Suo, Javier S. Turek, Vy A. Vo, Grant Wallace, Yida Wang, Hejia Zhang, Xia Zhu, Mihai Capota, Jonathan D. Cohen, Uri Hasson, Kai Li, Peter J. Ramadge, Nicholas B. Turk-Browne, Theodore L. Willke, Kenneth A. Norman, 2020. BrainIAK: The Brain Imaging Analysis Kit. preprint, [https://doi.org/10.31219/osf.io/db2ev](https://doi.org/10.31219/osf.io/db2ev)

2020-12-14 17:13 UTC, manojneuro requested changes

2020-12-14 17:13 UTC, manojneuro commented on _data/pubs.yml
> +      - Y. Peeta Li
LGTM.

2020-12-14 17:13 UTC, manojneuro commented on _data/pubs.yml
> +  journal: preprint
LGTM

2020-12-14 17:13 UTC, manojneuro commented on tutorials/index.md
> +
LGTM.

2020-12-14 17:13 UTC, manojneuro commented on tutorials/index.md
>  </div>
@gdoubleyew I just realized that there is one more file that hasn't been updated with the citations: https://brainiak.org/docs/index.html?highlight=citing.

2020-12-16 16:51 UTC, manojneuro approved these changes
LGTM

2020-12-16 18:58 UTC, merged